// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvnmfpbyhymkeojtfxfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2bm1mcGJ5aHlta2VvanRmeGZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODY2MzQsImV4cCI6MjA3MzM2MjYzNH0.0uYHzK65P6FcsQb7IXCaaYJ3ByfhcNNoRUbC-_rD9aQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});